package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.annotation.Generated;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2019-02-21T00:59:07.542+04:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "StakeholderService", 
                  wsdlLocation = "META-INF/wsdl/StakeholderService.wsdl",
                  targetNamespace = "http://tempuri.org/") 
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00", comments = "Apache CXF 3.1.7")
public class StakeholderService extends Service {

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public final static URL WSDL_LOCATION;

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public final static QName SERVICE = new QName("http://tempuri.org/", "StakeholderService");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public final static QName StakeholderServiceSoap12 = new QName("http://tempuri.org/", "StakeholderServiceSoap12");
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public final static QName StakeholderServiceSoap = new QName("http://tempuri.org/", "StakeholderServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/serhat/RedHat/accountsV2/DBX-MODC/poc/mocd-stakeholder-service/WebContent/wsdl/StakeholderService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StakeholderService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/serhat/RedHat/accountsV2/DBX-MODC/poc/mocd-stakeholder-service/WebContent/wsdl/StakeholderService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns StakeholderServiceSoap
     */
    @WebEndpoint(name = "StakeholderServiceSoap12")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderServiceSoap getStakeholderServiceSoap12() {
        return super.getPort(StakeholderServiceSoap12, StakeholderServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StakeholderServiceSoap
     */
    @WebEndpoint(name = "StakeholderServiceSoap12")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderServiceSoap getStakeholderServiceSoap12(WebServiceFeature... features) {
        return super.getPort(StakeholderServiceSoap12, StakeholderServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns StakeholderServiceSoap
     */
    @WebEndpoint(name = "StakeholderServiceSoap")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderServiceSoap getStakeholderServiceSoap() {
        return super.getPort(StakeholderServiceSoap, StakeholderServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StakeholderServiceSoap
     */
    @WebEndpoint(name = "StakeholderServiceSoap")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.542+04:00")
    public StakeholderServiceSoap getStakeholderServiceSoap(WebServiceFeature... features) {
        return super.getPort(StakeholderServiceSoap, StakeholderServiceSoap.class, features);
    }

}
