package org.tempuri;

import javax.annotation.Generated;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2019-02-21T00:59:07.539+04:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://tempuri.org/", name = "StakeholderServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
@Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.539+04:00", comments = "Apache CXF 3.1.7")
public interface StakeholderServiceSoap {

    @WebMethod(operationName = "GetStakeholderInfo", action = "http://tempuri.org/GetStakeholderInfo")
    @RequestWrapper(localName = "GetStakeholderInfo", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStakeholderInfo")
    @ResponseWrapper(localName = "GetStakeholderInfoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetStakeholderInfoResponse")
    @WebResult(name = "GetStakeholderInfoResult", targetNamespace = "http://tempuri.org/")
    @Generated(value = "org.apache.cxf.tools.wsdlto.WSDLToJava", date = "2019-02-21T00:59:07.539+04:00")
    public org.tempuri.StakeholderInfo getStakeholderInfo(
        @WebParam(name = "NameAR", targetNamespace = "http://tempuri.org/")
        java.lang.String nameAR,
        @WebParam(name = "NameEN", targetNamespace = "http://tempuri.org/")
        java.lang.String nameEN,
        @WebParam(name = "IdentityNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String identityNumber,
        @WebParam(name = "PhoneNumber", targetNamespace = "http://tempuri.org/")
        java.lang.String phoneNumber,
        @WebParam(name = "DateOfBirth", targetNamespace = "http://tempuri.org/")
        java.lang.String dateOfBirth,
        @WebParam(name = "Authentication", targetNamespace = "http://tempuri.org/", header = true)
        Authentication authentication
    );
}
